version: "3"
services:
  dns:
    build: Docker/DNS
    ports:
      - 53:53
    networks:
      virtual01:
        ipv4_address: 172.18.0.3
  node01:
    build: 
      dockerfile: ./Docker/Node/Dockerfile
      context: ./
    volumes:
      - ./source/:/root/Carlito/source
      - ./Docker/Node/01/:/root/Carlito/Config/
      - ./Docker/Node/01/secret:/root/Carlito/secret/
    ports:
      - 7777
    networks:
      virtual01:
        ipv4_address: 172.18.0.4
  node02:
    build: 
      dockerfile: ./Docker/Node/Dockerfile
      context: ./
    volumes:
      - ./source/:/root/Carlito/source
      - ./Docker/Node/02/:/root/Carlito/Config/
      - ./Docker/Node/02/secret:/root/Carlito/secret/
    ports:
      - 7777
    depends_on:
      - node01
    networks:
      virtual01:
        ipv4_address: 172.18.0.5
  node03:
    build: 
      dockerfile: ./Docker/Node/Dockerfile
      context: ./
    volumes:
      - ./source/:/root/Carlito/source
      - ./Docker/Node/03/:/root/Carlito/Config/
      - ./Docker/Node/03/secret:/root/Carlito/secret/
    ports:
      - 7777
    depends_on:
      - node02
    networks:
      virtual01:
        ipv4_address: 172.18.0.6
networks:
  virtual01:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
